url: "https://zhutaosheng.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/blog" # the subpath of your site, e.g. /blog
title: "Zhutao Sheng" # the name of your site, e.g. ACME Corp.
description: "Computational Chemist"
