menu:
- {name: 'People', url: '/people'}
- {name: 'Publications', url: '/publications'}
- {name: 'CV', url: '/cv'}
- {name: 'Contact', url: '/contact'}
- {name: 'Useful Links', url: '/useful_links'}
- {name: 'Blog', url: '/blog'}

people:
- {name: 'Graduate Student', title: 'Researcher', department: 'Single Molecules & Molecular Machines', institution: 'Rutgers, The State University of New Jersey', institution_address: 'Olson Hall, 73 Warren St, Rutgers University-Newark, Newark, NJ 07102', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Olson Hall, 73 Warren St, Rutgers University-Newark, Newark, NJ 07102', url: 'graduate-student'}

courses:
- {name: 'Vector Calculus', url: 'vector-calculus'}
- {name: 'Quantum Mechanics', url: 'quantum-mechanics'}
- {name: 'Stellar Structures', url: 'stellar-structures'}

social:
- {icon: 'github', link: 'contact'}
- {icon: 'twitter', link: 'contact'}
- {icon: 'instagram', link: 'contact'}
- {icon: 'linkedin', link: 'contact'}

contacts:
- {name: 'ZS', title: 'PhD', department: 'School of Arts & Sciences-Newark', institution: 'Rutgers, The State University of New Jersey', institution_address: 'Olson Hall, 73 Warren St, Rutgers University-Newark, Newark, NJ 07102', phone: '(000) 000-0000', email: 'zhutao.sheng@rutgers.edu', orcid: 'https://orcid.org/my-orcid?orcid=0000-0003-3355-1426',  office: 'Rutgers University-Newark', image: 'assets/img/contact.jpg'}
